apiVersion: v1
kind: ConfigMap
metadata:
  name: core-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432
  SPRING_DATASOURCE_USERNAME: technow
  SPRING_DATASOURCE_PASSWORD: technow
  MAIL_USERNAME: test
  MAIL_PASSWORD: test
  FRONTEND_URL: http://front-end-service:4173
  FROM_EMAIL: chelceacalin20@stud.ase.ro
  PYTHON_URL: http://python-service:5000
  NEWSLETTER_SECRET: htyxmhnBw46wPMFafDw2FE43ffj9G6sT
  REPORTS_SERVICE_URL: http://reports-service:8092/reporting
  MINIO_URL: http://minio-service:9000
  MINIO_ACCESS_KEY: admin
  MINIO_SECRET_KEY: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: calinmarius/core:1.1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: core-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: LoadBalancer
  selector:
    app: core
  ports:
    - port: 8080
      targetPort: 8080
