apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end-configmap
data:
  baseURL: http://core:8080/core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: calinmarius/front-end:1.1.0
          ports:
            - containerPort: 4176
          envFrom:
            - configMapRef:
                name: front-end-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  ports:
    - port: 4176
      targetPort: 4176
  type: LoadBalancer
