spring:
  application:
    name: report-service

server:
  port: 8092
  servlet:
    context-path: /reporting

# Api Documentation
springdoc:
  api-docs:
    path: /api-docs
    enabled: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1

